export const environment = {
    arrayGare: [
        { position_x: 136, position_Y: 409, gare_station: "Brest", cursor: 'pointer' },
        { position_x: 160, position_Y: 446, gare_station: "Quimper", cursor: 'pointer' },
        { position_x: 201, position_Y: 398, gare_station: 'Morlaix', cursor: 'pointer' },
        { position_x: 237, position_Y: 422, gare_station: "St Brieuc", cursor: 'pointer' },
        { position_x: 209, position_Y: 479, gare_station: "Lorient", cursor: 'pointer' },
        { position_x: 271, position_Y: 455, gare_station: "Rennes", cursor: "pointer" },
        { position_x: 284, position_Y: 428, gare_station: "Dol de Bretagne", cursor: "pointer" },
        { position_x: 299, position_Y: 404, gare_station: "St Malo", cursor: "pointer" },
        { position_x: 332, position_Y: 391, gare_station: "Granville", cursor: "pointer" },
        { position_x: 342, position_Y: 320, gare_station: "Cherbourg", cursor: "pointer" },
        { position_x: 269, position_Y: 522, gare_station: "Le Croisic", cursor: "pointer" },
        { position_x: 293, position_Y: 522, gare_station: "St Nazaire", cursor: "pointer" },
        { position_x: 331, position_Y: 534, gare_station: "Nantes", cursor: "pointer" },
        { position_x: 340, position_Y: 584, gare_station: "La Roche sur Yon", cursor: "pointer" },
        { position_x: 463, position_Y: 330, gare_station: "Le Havre", cursor: "pointer" },
        { position_x: 452, position_Y: 348, gare_station: "Trouville Deauville", cursor: "pointer" },
        { position_x: 441, position_Y: 352, gare_station: "Dives Cabourg", cursor: "pointer" },
        { position_x: 429, position_Y: 360, gare_station: "Caen", cursor: "pointer" },
        { position_x: 464, position_Y: 365, gare_station: "Lisieux", cursor: "pointer" },
        { position_x: 449, position_Y: 408, gare_station: "Argentan", cursor: "pointer" },
        { position_x: 458, position_Y: 418, gare_station: "Surdon", cursor: "pointer" },
        { position_x: 451, position_Y: 435, gare_station: "Alençon", cursor: "pointer" },
        { position_x: 383, position_Y: 453, gare_station: "Laval", cursor: "pointer" },
        { position_x: 399, position_Y: 500, gare_station: "Angers", cursor: "pointer" },
        { position_x: 455, position_Y: 586, gare_station: "Futuroscope TGV", cursor: "pointer" },
        { position_x: 489, position_Y: 524, gare_station: "Tours", cursor: "pointer" },
        { position_x: 491, position_Y: 540, gare_station: "St pierre des Corps", cursor: "pointer" },
        { position_x: 405, position_Y: 618, gare_station: "Niort", cursor: "pointer" },
        { position_x: 517, position_Y: 304, gare_station: "Dieppe", cursor: "pointer" },
        { position_x: 513, position_Y: 340, gare_station: "Rouen", cursor: "pointer" },
        { position_x: 560, position_Y: 400, gare_station: "Versaille Chantier", cursor: "pointer" },
        { position_x: 523, position_Y: 430, gare_station: "Chartres", cursor: "pointer" },
        { position_x: 452, position_Y: 474, gare_station: "Le Mans", cursor: "pointer" },
        { position_x: 575, position_Y: 414, gare_station: "Massy TGV", cursor: "pointer" },
        { position_x: 624, position_Y: 364, gare_station: "aéroport cdg tgv", cursor: "pointer" },
        { position_x: 639, position_Y: 398, gare_station: "marne la vallée tgv", cursor: "pointer" },
        { position_x: 568, position_Y: 487, gare_station: "Les Aubrais Orléans", cursor: "pointer" },
        { position_x: 570, position_Y: 536, gare_station: "Vierzon", cursor: "pointer" },
        { position_x: 609, position_Y: 541, gare_station: "Bourges", cursor: "pointer" },
        { position_x: 547, position_Y: 587, gare_station: "Châteauroux", cursor: "pointer" },
        { position_x: 627, position_Y: 560, gare_station: "Saincaize", cursor: "pointer" },
        { position_x: 649, position_Y: 551, gare_station: "Nevers", cursor: "pointer" },
        { position_x: 618, position_Y: 603, gare_station: "Montluçon", cursor: "pointer" },
        { position_x: 584, position_Y: 635, gare_station: "Guéret", cursor: "pointer" },
        { position_x: 525, position_Y: 656, gare_station: "Limoges", cursor: "pointer" },
        { position_x: 464, position_Y: 679, gare_station: "Angoulême", cursor: "pointer" },
        { position_x: 410, position_Y: 690, gare_station: "Saintes", cursor: "pointer" },
        { position_x: 367, position_Y: 639, gare_station: "La Rochelle", cursor: "pointer" },
        { position_x: 394, position_Y: 742, gare_station: "Bordeaux", cursor: "pointer" },
        { position_x: 390, position_Y: 760, gare_station: "Facture", cursor: "pointer" },
        { position_x: 372, position_Y: 762, gare_station: "Arcachon", cursor: "pointer" },
        { position_x: 372, position_Y: 828, gare_station: "Dax", cursor: "pointer" },
        { position_x: 338, position_Y: 857, gare_station: "Bayonne", cursor: "pointer" },
        { position_x: 316, position_Y: 873, gare_station: "Hendaye", cursor: "pointer" },
        { position_x: 402, position_Y: 878, gare_station: "Pau", cursor: "pointer" },
        { position_x: 426, position_Y: 900, gare_station: "Lourdes", cursor: "pointer" },
        { position_x: 444, position_Y: 883, gare_station: "Tarbe", cursor: "pointer" },
        { position_x: 541, position_Y: 863, gare_station: "Toulouse", cursor: "pointer" },
        { position_x: 585, position_Y: 897, gare_station: "Carcassonne", cursor: "pointer" },
        { position_x: 631, position_Y: 901, gare_station: "Narbonne", cursor: "pointer" },
        { position_x: 627, position_Y: 942, gare_station: "Perpignan", cursor: "pointer" },
        { position_x: 650, position_Y: 959, gare_station: "Cerbère", cursor: "pointer" },
        { position_x: 653, position_Y: 879, gare_station: "Bézier", cursor: "pointer" },
        { position_x: 702, position_Y: 880, gare_station: "Sète", cursor: "pointer" },
        { position_x: 730, position_Y: 857, gare_station: "Montpellier", cursor: "pointer" },
        { position_x: 753, position_Y: 832, gare_station: "Nîmes", cursor: "pointer" },
        { position_x: 788, position_Y: 843, gare_station: "Avignon", cursor: "pointer" },
        { position_x: 790, position_Y: 831, gare_station: "Avignon tgv", cursor: "pointer" },
        { position_x: 827, position_Y: 879, gare_station: "Aix en provence tgv", cursor: "pointer" },
        { position_x: 832, position_Y: 889, gare_station: "Marseille", cursor: "pointer" },
        { position_x: 878, position_Y: 901, gare_station: "Toulon", cursor: "pointer" },
        { position_x: 940, position_Y: 860, gare_station: "Cannes", cursor: "pointer" },
        { position_x: 962, position_Y: 840, gare_station: "Nice", cursor: "pointer" },
        { position_x: 980, position_Y: 829, gare_station: "Vintimille", cursor: "pointer" },
        { position_x: 497, position_Y: 721, gare_station: "Périgueux", cursor: "pointer" },
        { position_x: 479, position_Y: 801, gare_station: "Agen", cursor: "pointer" },
        { position_x: 542, position_Y: 825, gare_station: "Montauban", cursor: "pointer" },
        { position_x: 543, position_Y: 790, gare_station: "Cahors", cursor: "pointer" },
        { position_x: 544, position_Y: 730, gare_station: "Brive la Gaillarde", cursor: "pointer" },
        { position_x: 563, position_Y: 709, gare_station: "Tulle", cursor: "pointer" },
        { position_x: 582, position_Y: 763, gare_station: "Figeac", cursor: "pointer" },
        { position_x: 629, position_Y: 742, gare_station: "Aurillac", cursor: "pointer" },
        { position_x: 609, position_Y: 685, gare_station: "Ussel", cursor: "pointer" },
        { position_x: 623, position_Y: 793, gare_station: "Rodez", cursor: "pointer" },
        { position_x: 655, position_Y: 810, gare_station: "Millau", cursor: "pointer" },
        { position_x: 657, position_Y: 671, gare_station: "Clermont Ferrend", cursor: "pointer" },
        { position_x: 654, position_Y: 637, gare_station: "Gannat", cursor: "pointer" },
        { position_x: 677, position_Y: 639, gare_station: "Vichy", cursor: "pointer" },
        { position_x: 684, position_Y: 621, gare_station: "St Germains des Fossés", cursor: "pointer" },
        { position_x: 667, position_Y: 596, gare_station: "Moulins sur Allier", cursor: "pointer" },
        { position_x: 725, position_Y: 597, gare_station: "Paray le Monial", cursor: "pointer" },
        { position_x: 735, position_Y: 587, gare_station: "Montceau les Mines", cursor: "pointer" },
        { position_x: 766, position_Y: 606, gare_station: "Mâcon TGV", cursor: "pointer" },
        { position_x: 801, position_Y: 622, gare_station: "Bourg en Bresse", cursor: "pointer" },
        { position_x: 787, position_Y: 665, gare_station: "Lyon", cursor: "pointer" },
        { position_x: 795, position_Y: 741, gare_station: "Valence TGV", cursor: "pointer" },
        { position_x: 785, position_Y: 739, gare_station: "Valence Ville", cursor: "pointer" },
        { position_x: 460, position_Y: 602, gare_station: "Poitiers", cursor: "pointer" },
        { position_x: 542, position_Y: 509, gare_station: "Blois", cursor: "pointer" },
        { position_x: 598, position_Y: 396, gare_station: "Paris", cursor: "pointer" },
        { position_x: 596, position_Y: 360, gare_station: "Creil", cursor: "pointer" },
        { position_x: 552, position_Y: 231, gare_station: "Boulogne", cursor: "pointer" },
        { position_x: 561, position_Y: 217, gare_station: "Calais", cursor: "pointer" },
        { position_x: 573, position_Y: 200, gare_station: "Dunkerque", cursor: "pointer" },
        { position_x: 648, position_Y: 215, gare_station: "Tourcoing", cursor: "pointer" },
        { position_x: 644, position_Y: 221, gare_station: "Roubaix", cursor: "pointer" },
        { position_x: 643, position_Y: 234, gare_station: "Lille", cursor: "pointer" },
        { position_x: 593, position_Y: 247, gare_station: "Bethune", cursor: "pointer" },
        { position_x: 593, position_Y: 259, gare_station: "Lens", cursor: "pointer" },
        { position_x: 639, position_Y: 269, gare_station: "Douai", cursor: "pointer" },
        { position_x: 621, position_Y: 285, gare_station: "Arras", cursor: "pointer" },
        { position_x: 602, position_Y: 316, gare_station: "Amiens", cursor: "pointer" },
        { position_x: 621, position_Y: 320, gare_station: "TGV Haute Picardie", cursor: "pointer" },
        { position_x: 652, position_Y: 321, gare_station: "St Quentin", cursor: "pointer" },
        { position_x: 633, position_Y: 338, gare_station: "Compiègne", cursor: "pointer" },
        { position_x: 673, position_Y: 354, gare_station: "Laon", cursor: "pointer" },
        { position_x: 702, position_Y: 357, gare_station: "Reims", cursor: "pointer" },
        { position_x: 701, position_Y: 370, gare_station: "Champagne Ardennes TGV", cursor: "pointer" },
        { position_x: 702, position_Y: 388, gare_station: "Epernay", cursor: "pointer" },
        { position_x: 710, position_Y: 438, gare_station: "Troyes", cursor: "pointer" },
        { position_x: 737, position_Y: 389, gare_station: "Châlons en Champagne", cursor: "pointer" },
        { position_x: 759, position_Y: 391, gare_station: "Vitry le François", cursor: "pointer" },
        { position_x: 793, position_Y: 397, gare_station: "Bar le Duc", cursor: "pointer" },
        { position_x: 785, position_Y: 410, gare_station: "St Dizier", cursor: "pointer" },
        { position_x: 789, position_Y: 473, gare_station: "Chaumont", cursor: "pointer" },
        { position_x: 822, position_Y: 492, gare_station: "Culmont Chalindrey", cursor: "pointer" },
        { position_x: 818, position_Y: 424, gare_station: "Toul", cursor: "pointer" },
        { position_x: 811, position_Y: 340, gare_station: "Longwy", cursor: "pointer" },
        { position_x: 843, position_Y: 340, gare_station: "Thionville", cursor: "pointer" },
        { position_x: 846, position_Y: 362, gare_station: "Metz", cursor: "pointer" },
        { position_x: 800, position_Y: 357, gare_station: "Verdun", cursor: "pointer" },
        { position_x: 892, position_Y: 347, gare_station: "Forbach", cursor: "pointer" },
        { position_x: 757, position_Y: 317, gare_station: "Charleville Mézières", cursor: "pointer" },
        { position_x: 678, position_Y: 263, gare_station: "Valenciennes", cursor: "pointer" },
        { position_x: 696, position_Y: 279, gare_station: "Aulnoye aymeries", cursor: "pointer" },
        { position_x: 710, position_Y: 266, gare_station: "Maubeuge", cursor: "pointer" },
        { position_x: 722, position_Y: 258, gare_station: "Jeumont frontière", cursor: "pointer" },
        { position_x: 703, position_Y: 243, gare_station: "Quévy frontière", cursor: "pointer" },
        { position_x: 791, position_Y: 380, gare_station: "Meuse TGV", cursor: "pointer" },
        { position_x: 836, position_Y: 386, gare_station: "Lorraine TGV", cursor: "pointer" },
        { position_x: 869, position_Y: 415, gare_station: "Nancy", cursor: "pointer" },
        { position_x: 886, position_Y: 410, gare_station: "Luneville", cursor: "pointer" },
        { position_x: 917, position_Y: 400, gare_station: "Sarrebourg", cursor: "pointer" },
        { position_x: 905, position_Y: 435, gare_station: "St Dié", cursor: "pointer" },
        { position_x: 863, position_Y: 453, gare_station: "Epinal", cursor: "pointer" },
        { position_x: 958, position_Y: 412, gare_station: "Strasbourg", cursor: "pointer" },
        { position_x: 941, position_Y: 454, gare_station: "Colmar", cursor: "pointer" },
        { position_x: 942, position_Y: 494, gare_station: "Mulhouse", cursor: "pointer" },
        { position_x: 964, position_Y: 513, gare_station: "Basel", cursor: "pointer" },
        { position_x: 896, position_Y: 503, gare_station: "Belford", cursor: "pointer" },
        { position_x: 883, position_Y: 517, gare_station: "Montbéliard", cursor: "pointer" },
        { position_x: 868, position_Y: 529, gare_station: "Besançon", cursor: "pointer" },
        { position_x: 798, position_Y: 530, gare_station: "Dijon", cursor: "pointer" },
        { position_x: 821, position_Y: 549, gare_station: "Dôle", cursor: "pointer" },
        { position_x: 849, position_Y: 564, gare_station: "Mouchard", cursor: "pointer" },
        { position_x: 777, position_Y: 546, gare_station: "Chagny", cursor: "pointer" },
        { position_x: 778, position_Y: 582, gare_station: "Chalon sur Saône", cursor: "pointer" },
        { position_x: 776, position_Y: 600, gare_station: "Mâcon Ville", cursor: "pointer" },
        { position_x: 857, position_Y: 632, gare_station: "Bellegarde", cursor: "pointer" },
        { position_x: 857, position_Y: 615, gare_station: "Genève", cursor: "pointer" },
        { position_x: 896, position_Y: 603, gare_station: "Evian", cursor: "pointer" },
        { position_x: 911, position_Y: 657, gare_station: "St Gervais les Bains", cursor: "pointer" },
        { position_x: 729, position_Y: 650, gare_station: "Roanne", cursor: "pointer" },
        { position_x: 746, position_Y: 694, gare_station: "St Etienne", cursor: "pointer" },
        { position_x: 767, position_Y: 683, gare_station: "St Chamond", cursor: "pointer" },
        { position_x: 785, position_Y: 705, gare_station: "Vienne", cursor: "pointer" },
        { position_x: 699, position_Y: 715, gare_station: "Le Puy en Velay", cursor: "pointer" },
        { position_x: 727, position_Y: 804, gare_station: "Alès", cursor: "pointer" },
        { position_x: 832, position_Y: 700, gare_station: "Moirans", cursor: "pointer" },
        { position_x: 842, position_Y: 711, gare_station: "Grenoble", cursor: "pointer" },
        { position_x: 856, position_Y: 685, gare_station: "Chambéry", cursor: "pointer" },
        { position_x: 857, position_Y: 664, gare_station: "Aix les Bains", cursor: "pointer" },
        { position_x: 856, position_Y: 651, gare_station: "Culoz", cursor: "pointer" },
        { position_x: 879, position_Y: 646, gare_station: "Annecy", cursor: "pointer" },
        { position_x: 929, position_Y: 690, gare_station: "Bourg St Maurice", cursor: "pointer" },
        { position_x: 917, position_Y: 711, gare_station: "Modane", cursor: "pointer" },
        { position_x: 912, position_Y: 740, gare_station: "Briançon", cursor: "pointer" },
        { position_x: 908, position_Y: 767, gare_station: "Gap", cursor: "pointer" },
        { position_x: 856, position_Y: 775, gare_station: "Veynes dévoluy", cursor: "pointer" },
        { position_x: 836, position_Y: 851, gare_station: "Aix en Provence", cursor: "pointer" },
    ],
    listGif: [
        { index: 0, src: "assets/emoj/8583-yoyomonkey-thinkinghard.gif" },
        { index: 1, src: "assets/emoj/spongebob-pageflip.gif" },
        { index: 2, src: "assets/emoj/cicimonkey-blush.gif" },
        { index: 3, src: "assets/emoj/nyanparrot.gif" },
        { index: 4, src: "assets/emoj/MegurineLuka_Applause1.gif" },
        { index: 5, src: "assets/emoj/catgirlears.gif" },
        { index: 6, src: "assets/emoj/MegurineLuka_Applause1.gif" },
        { index: 7, src: "assets/emoj/giphy1.gif" },
        { index: 8, src: "assets/emoj/giphy2.gif" },
        { index: 9, src: "assets/emoj/giphy3.gif" },
        { index: 10, src: "assets/emoj/giphy.gif" },
        { index: 11, src: "assets/emoj/no.gif" },
        { index: 12, src: "assets/emoj/chaton.gif" }
    ]
}